### ISSUE TITLE
xf86 definitions

### ISSUE THREAD

**Issue by pfps** [barneygale/keysymdef#1]
Are there plans to add the xf86 definitions?  These are considered to be standard these days.

**Comment by barneygale** [comment]
Sorry for the long wait. Fixed in 6c7883446b17e0a1fe03dd2ef2ac67c1ecb76e1b, released as 1.1.0.

**Comment by barneygale** [comment]
Sorry, just realised there were some naming collisions, so I've split them out into a separate list - `keysymdef.xf86keysym` - and released 1.2.0.
